# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem_solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrol', models.CharField(max_length=15)),
                ('solution', models.TextField()),
                ('correct', models.BooleanField(default='False')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
    ]
